class Fan{
	public static void main(String[] anything){
	 System.out.println("1.SLEEK DESIGN: Atomberg Renesa Enzel has a compact body with sleek designer blades and an LED speed indicator that elevates the décor of your room.");
	 System.out.println("2.ENERGY-EFFICIENT BLDC TECHNOLOGY: Atomberg Renesa Enzel comes with a 5-star rated energy-efficient BLDC motor. This 5-star rated fan consumes only 35W at top speed, saving up to 65% in electricity consumption compared to unrated fans.");
	 System.out.println("3.HIGH PERFORMANCE: Atomberg Renesa Enzel offers high air delivery of 225 CMM, ensuring optimum airflow to every corner of your room. It has noise levels of less than 57 dB, making it much quieter than most regular fans which operate at 65 dB or more.");
	 System.out.println("4.REMOTE CONTROL CONVENIENCE: Atomberg Renesa Enzel comes with a Smart IR Remote for effortless control, allowing you to adjust speed, activate Boost Mode, set timers, or enable Sleep Mode with a single click. This remote is universal across Atomberg fans and does not need to be paired, allowing easy operation.");
	 System.out.println("5.LED SPEED INDICATOR: Atomberg Renesa Enzel features an LED light that glows to indicate functions like turning the fan on/off, adjusting the speed, or setting the timer or sleep mode, providing clear feedback for each operation via the remote.");
	 System.out.println("6.FALSE CEILING COMPATIBILITY: This fan is suitable for false ceilings or low ceiling height since it offers an additional ceiling plate beside a canopy set. If the full height is available, can use the bottom and top canopy, else for low heights or false ceilings, can use the top ceiling plate with the bottom canopy. This ensures hassle-free installation in all circumstances.");
	 System.out.println("7.RELIABILITY: Atomberg Renesa Enzel is a bestselling ceiling fan from the Atomberg portfolio, makers of India’s No. 1 BLDC fans, with over 1crore+ happy customers. Every product from Atomberg undergoes rigorous testing to minimize failure rates and ensure top-class performance and efficiency before reaching you. It is entirely designed and manufactured in India, at India’s largest BLDC fan manufacturing plant in Chakan, Pune");
	 System.out.println("8.CONSISTENT SPEED EVEN AT LOW VOLTAGE: Atomberg Renesa Enzel ceiling fan runs with no drop in speed during voltage fluctuations ranging between 165V-285V, thereby maintaining consistency. It runs 3X longer on an inverter battery when compared to ordinary fans, ensuring uninterrupted airflow even during power outages.");
	}
}