package com.xworkz.libraryapp.constants;

public enum Genre {
    FICTION,NON_FICTION,ROMANCE,SCI_FI,FANTASY,MYSTERY,HORROR,ADVENTURE,BIOGRAPHY,SELF_HELP,HISTORY,SCIENCE,PHILOSOPHY,TRAVEL,TRUE_CRIME,SPIRITUALITY,BUSINESS,HEALTH,POETRY,DRAMA;
}
